FROM python:3.12-slim

WORKDIR /app

COPY backend/requirements-worker.txt .

RUN pip install --no-cache-dir -r requirements-worker.txt

COPY backend ./backend

CMD ["python", "-m", "backend.run-worker"]